name: QuarryPlugin
version: '1.0' # Change this to match your project version
main: org.plugin.quarryplugin.QuarryPlugin
api-version: '1.16'
description: A simple plugin to create a quarry that automatically mines ores.
author: Gblack54